apiVersion: v1
kind: Namespace
metadata:
  name: conncheck
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conncheck-controller
  namespace: conncheck
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conncheck-controller
rules:
- verbs: [get]
  resources: [daemonsets]
  apiGroups: ["apps", "extensions"]
- verbs: [list]
  resources: [pods, nodes]
  apiGroups: [""]
- verbs: [get]
  resources: [services]
  apiGroups: [""]
- verbs: [create]
  resources: [replicasets]
  apiGroups: ["apps"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: conncheck-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conncheck-controller
subjects:
- kind: ServiceAccount
  name: conncheck-controller
  namespace: conncheck
---
apiVersion: v1
kind: Pod
metadata:
  name: conncheck-controller
  namespace: conncheck
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  restartPolicy: Never
  serviceAccountName: conncheck-controller
  containers:
  - image: weibeld/k8s-conncheck-controller
    name: conncheck-controller
    imagePullPolicy: Always
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: conncheck-service
  namespace: conncheck
spec:
  selector:
    app: conncheck-target
  ports:
  - port: 1024
    targetPort: 1024
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: conncheck-target
  namespace: conncheck
spec:
  selector:
    matchLabels:
      app: conncheck-target
  template:
    metadata:
      labels:
        app: conncheck-target
    spec:
      containers:
      - image: weibeld/k8s-conncheck-target
        name: conncheck-target
