apiVersion: v1
kind: ServiceAccount
metadata:
  name: conncheck-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conncheck-controller
rules:
- apiGroups: [""]
  resources: [pods, nodes]
  verbs: [list]
- apiGroups: [""]
  resources: [pods]
  verbs: [get, create]
- apiGroups: [""]
  resources: [pods, pods/log]
  verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: conncheck-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conncheck-controller
subjects:
- kind: ServiceAccount
  name: conncheck-controller
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: conncheck-controller
spec:
  hostNetwork: true
  serviceAccountName: conncheck-controller
  containers:
  - image: weibeld/k8s-conncheck-controller
    name: conncheck-controller
    command: ["sleep", "infinity"]
    imagePullPolicy: Always
    volumeMounts:
      - name: kubelet-conf
        mountPath: /etc/kubernetes/kubelet.conf
  volumes:
    - name: kubelet-conf
      hostPath:
        path: /etc/kubernetes/kubelet.conf
        type: File
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: conncheck-target
spec:
  selector:
    matchLabels:
      app: conncheck-target
  template:
    metadata:
      labels:
        app: conncheck-target
    spec:
      containers:
      - image: alpine
        name: alpine
        command: ["sleep", "infinity"]
